info:
    description:
        "MailRest REST API. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.mail.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "MailRest"
    version: v1.0
openapi: 3.0.1
components:
   schemas:
      Mail:
        description: "This is the rest builder for send email"
        properties:
            Email:
              type: string
  
         
paths: 
    "/mail":
        post:
            operationId: sendEmail
            requestBody:
                description: Write E-mail Id to get email
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Mail"
                          
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Mail"
            responses:
              200:
                description: Successful operation
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Mail"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Mail"
                    
            tags: ["Mail"]              